version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: typescript
    versions:
    - "> 3.9.7"
  - dependency-name: tslib
    versions:
    - 2.1.0
