cache_key: &cache_key tscc-{{ checksum "yarn.lock" }}
save_cache: &save_cache
  save_cache:
    key: *cache_key
    paths:
      - "node_modules"

version: 2

jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/openjdk:9-node
    working_directory: ~/tscc
    steps:
      - checkout
      - run:
          name: update node
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
      - restore_cache:
          key: *cache_key
      - run: yarn install
      - run: yarn lerna bootstrap
      - run:
          name: run tests
          command: yarn jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/results.xml"
      - run:
          name: compile typescript
          command: yarn lerna exec -- -- tsc --noEmit
      - *save_cache
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
